<?php

return [

    'members' => [
              'create' => [
                      'title' => 'Add Member',
                      'blade' => 'members.create',
                      'header' => 'Add',
                      'header-muted' => 'New Member',
                      'form' => [
                            'action' => 'members.create',
                            'method' => 'POST',
                            'inputs' => [
                                    'name' => [
                                          'size' => 12,
                                          'input' => 'input',
                                          'for' => 'name',
                                          'label' => 'Member Name',
                                          'name' => 'name',
                                          'placeholder' => false,
                                          'type' => 'text',
                                          'text' => false,
                                          'id' => 'name',
                                          'class' => 'form-control',
                                          'value' => '',
                                          'newrow' => false,
                                          ],
                                    'submit' => [
                                          'size' => 3,
                                          'input' => 'button',
                                          'for' => false,
                                          'label' => false,
                                          'name' => 'submit',
                                          'placeholder' => false,
                                          'type' => 'submit',
                                          'text' => 'Add New Member',
                                          'id' => 'submit',
                                          'class' => 'btn btn-lg btn-primary',
                                          'value' => false,
                                          'newrow' => true,
                                          ],
                                    ],
                            ],
              ],
              'edit' => [
                      'title' => 'Edit Member',
                      'blade' => 'members.edit',
                      'header' => 'Edit',
                      'header-muted' => 'Existing Member',
                      'form' => [
                            'action' => 'members.edit',
                            'method' => 'POST',
                            'inputs' => [
                                    'name' => [
                                          'size' => 12,
                                          'input' => 'input',
                                          'for' => 'name',
                                          'label' => 'Member Name',
                                          'name' => 'name',
                                          'placeholder' => false,
                                          'type' => 'text',
                                          'text' => false,
                                          'id' => 'name',
                                          'class' => 'form-control',
                                          'value' => 'name',
                                          'newrow' => false,
                                          ],
                                    'id' => [
                                          'size' => 12,
                                          'input' => 'input',
                                          'for' => false,
                                          'label' => false,
                                          'name' => 'id',
                                          'placeholder' => false,
                                          'type' => 'hidden',
                                          'text' => false,
                                          'id' => 'id',
                                          'class' => 'form-control',
                                          'value' => 'id',
                                          'newrow' => false,
                                          ],
                                    'submit' => [
                                          'size' => 4,
                                          'input' => 'button',
                                          'for' => false,
                                          'label' => false,
                                          'name' => 'submit',
                                          'placeholder' => false,
                                          'type' => 'submit',
                                          'text' => 'Update Existing Member',
                                          'id' => 'submit',
                                          'class' => 'btn btn-lg btn-primary',
                                          'value' => false,
                                          'newrow' => true,
                                          ],
                                    ],
                            ],
              ],

    ],
    'scores' => [
              'create' => [
                      'title' => 'Add Score',
                      'blade' => 'scores.create',
                      'header' => 'Add',
                      'header-muted' => 'New Score',
                      'form' => [
                            'action' => 'scores.create',
                            'method' => 'POST',
                            'inputs' => [
                                    'member_id' => [
                                          'size' => 12,
                                          'input' => 'select',
                                          'for' => 'member_id',
                                          'label' => 'Members',
                                          'name' => 'member_id',
                                          'placeholder' => false,
                                          'type' => 'select',
                                          'text' => false,
                                          'id' => 'member_id',
                                          'class' => 'form-control',
                                          'value' => '',
                                          'option' => 'members',
                                          'newrow' => false,
                                          ],
                                    'score' => [
                                          'size' => 12,
                                          'input' => 'input',
                                          'for' => 'score',
                                          'label' => 'Score',
                                          'name' => 'score',
                                          'placeholder' => false,
                                          'type' => 'number',
                                          'text' => false,
                                          'id' => 'score',
                                          'class' => 'form-control',
                                          'value' => 0,
                                          'newrow' => false,
                                          ],
                                    'submit' => [
                                          'size' => 4,
                                          'input' => 'button',
                                          'for' => false,
                                          'label' => false,
                                          'name' => 'submit',
                                          'placeholder' => false,
                                          'type' => 'submit',
                                          'text' => 'Add New Score',
                                          'id' => 'submit',
                                          'class' => 'btn btn-lg btn-primary',
                                          'value' => false,
                                          'newrow' => true,
                                          ],
                                    ],
                            ],
              ],
              'edit' => [
                      'title' => 'Edit Score',
                      'blade' => 'scores.edit',
                      'header' => 'Edit',
                      'header-muted' => 'Existing Score',
                      'form' => [
                            'action' => 'scores.edit',
                            'method' => 'POST',
                            'inputs' => [
                                    'member_id' => [
                                          'size' => 12,
                                          'input' => 'select',
                                          'for' => 'member_id',
                                          'label' => 'Members',
                                          'name' => 'member_id',
                                          'placeholder' => false,
                                          'type' => 'select',
                                          'text' => false,
                                          'id' => 'member_id',
                                          'class' => 'form-control',
                                          'value' => 'member_id',
                                          'option' => 'members',
                                          'newrow' => false,
                                          ],
                                    'id' => [
                                          'size' => 12,
                                          'input' => 'input',
                                          'for' => false,
                                          'label' => false,
                                          'name' => 'id',
                                          'placeholder' => false,
                                          'type' => 'hidden',
                                          'text' => false,
                                          'id' => 'id',
                                          'class' => 'form-control',
                                          'value' => 'id',
                                          'newrow' => false,
                                          ],
                                    'submit' => [
                                          'size' => 4,
                                          'input' => 'button',
                                          'for' => false,
                                          'label' => false,
                                          'name' => 'submit',
                                          'placeholder' => false,
                                          'type' => 'submit',
                                          'text' => 'Update Existing Score',
                                          'id' => 'submit',
                                          'class' => 'btn btn-lg btn-primary',
                                          'value' => false,
                                          'newrow' => true,
                                          ],
                                    ],
                            ],
              ],

    ],

];
